name: Test Runner  # Workflow name

#
#on:
#  workflow_dispatch:

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  my-job:
    runs-on: aws-runner-t4g.large
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Check Runner
        run: echo "Running on aws-runner-t4g.large"

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Print Current Directory
        run: pwd

      - name: List Files in Repository
        run: ls -la /home/ubuntu
